### ISSUE TITLE
About the test result

### ISSUE THREAD

**Issue by goodluckcwl** [zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment#1]
Can you provide the test result on 300W?

**Comment by zjjMaiMai** [comment]
i do not test all dataset yet , you can test it by yourself. 

in my experiment, the err of challenging subset is 7.7.
i think the data augmentation is not good in my implementation.

**Comment by Edwardmark** [comment]
@goodluckcwl what is your test result on 300W public test set? I trained on 300W trainset, and test on 300W public test set, the inter-ocular error is 5.6% while in paper is 3.59%.

**Comment by xxllp** [comment]
@Edwardmark ,你在哪下的test 数据，我没看到链接哈

**Comment by xxllp** [comment]
方便给个下载方式嘛

**Comment by Edwardmark** [comment]
@xxllp https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/

**Comment by xxllp** [comment]
@Edwardmark ，我下载了这个数据，就是没看到test 的部分

**Comment by Edwardmark** [comment]
@xxllp 仔细阅读官网说明啊，兄弟，论文里有介绍的

**Comment by destiny311** [comment]
> 
> 
> @xxllp https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/

请问其他的测试例如inter-pupil error 应该怎么实现呢，初入门实在不晓得，希望大神可以指导一波。

**Comment by destiny311** [comment]
@Edwardmark 可以给一下测试代码吗，在线等。谢谢啦
