### ISSUE TITLE
Function of AffineImage

### ISSUE THREAD

**Issue by soul-place** [zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment#2]
There is something wrong when test on CPU about affineImage function, the error is ( InvalidArgumentError flat indices[12543,:]=[111,112] does not index into param(shape:[112,112])), I locate the error at  OutImage = (1-dx)*(1-dy)*tf.gather_nd()...........
Running on the GPU test good, but the CPU occurs above error

**Comment by zjjMaiMai** [comment]
could you provide more deteil ? What version of tensorflow do you use?

I will test it later, thaks for your report!

**Comment by soul-place** [comment]
My tf version 1.1.0, training the code no problem. I solve the problem when just set (SrcPixels=tf.clip_by_value(SrcPixels,0,IMGSIZE-2)) in line 72 of DAN.py for function Do
