### ISSUE TITLE
how to predict one img?

### ISSUE THREAD

**Issue by jiangtaoo2333** [zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment#24]
thanks for you sharing.
it seemed that author used to try to predict on video.
can you share the code?
Your help will be greatly appreciated.

**Comment by MrX1990** [comment]
In DAN_V2.py:

    def video_input_fn(data_dir,img_size,num_lmark):
    # video = cv2.VideoCapture(data_dir)

    def _get_frame():
        # while True:
            # _,frame = video.read()
            # if len(frame.shape) == 3:
            #     frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        path = 'data/image.jpg'
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        frame = cv2.resize(img,(img_size,img_size)).astype(np.float32)
        yield (frame,np.zeros([num_lmark,2],np.float32))

    def input_fn():
        dataset = tf.data.Dataset.from_generator(_get_frame,(tf.float32,tf.float32),(tf.TensorShape([img_size,img_size]),tf.TensorShape([num_lmark,2])))
        return dataset

    return input_fn

In dan_run_loop.py:

    if flags.mode == tf.estimator.ModeKeys.PREDICT:
        import cv2
        predict_results = estimator.predict(input_function)
        for x in predict_results:
            landmark = x['s2_ret']
            img = x['img']
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
            for lm in landmark:
              cv2.circle(img, (lm[0], lm[1]), 1, (0,0,255), -1)

            # cv2.imshow('t',img)
            # cv2.waitKey(30)
            cv2.imwrite('data/image_predict.jpg', img)
        return

**Comment by jiangtaoo2333** [comment]
@MrX1990  thanks a lot.

**Comment by zhouyufei0001** [comment]
> In DAN_V2.py:
> 
> ```
> def video_input_fn(data_dir,img_size,num_lmark):
> # video = cv2.VideoCapture(data_dir)
> 
> def _get_frame():
>     # while True:
>         # _,frame = video.read()
>         # if len(frame.shape) == 3:
>         #     frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
>     path = 'data/image.jpg'
>     img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
>     frame = cv2.resize(img,(img_size,img_size)).astype(np.float32)
>     yield (frame,np.zeros([num_lmark,2],np.float32))
> 
> def input_fn():
>     dataset = tf.data.Dataset.from_generator(_get_frame,(tf.float32,tf.float32),(tf.TensorShape([img_size,img_size]),tf.TensorShape([num_lmark,2])))
>     return dataset
> 
> return input_fn
> ```
> In dan_run_loop.py:
> 
> ```
> if flags.mode == tf.estimator.ModeKeys.PREDICT:
>     import cv2
>     predict_results = estimator.predict(input_function)
>     for x in predict_results:
>         landmark = x['s2_ret']
>         img = x['img']
>         img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
>         for lm in landmark:
>           cv2.circle(img, (lm[0], lm[1]), 1, (0,0,255), -1)
> 
>         # cv2.imshow('t',img)
>         # cv2.waitKey(30)
>         cv2.imwrite('data/image_predict.jpg', img)
>     return
> ```

the landmarks are not right

**Comment by Susia00** [comment]
@MrX1990 the landmark seems to predict the crop image, while img = x['img'] is the gray original image?

**Comment by kelisiya** [comment]
> In DAN_V2.py:
> 
> ```
> def video_input_fn(data_dir,img_size,num_lmark):
> # video = cv2.VideoCapture(data_dir)
> 
> def _get_frame():
>     # while True:
>         # _,frame = video.read()
>         # if len(frame.shape) == 3:
>         #     frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
>     path = 'data/image.jpg'
>     img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
>     frame = cv2.resize(img,(img_size,img_size)).astype(np.float32)
>     yield (frame,np.zeros([num_lmark,2],np.float32))
> 
> def input_fn():
>     dataset = tf.data.Dataset.from_generator(_get_frame,(tf.float32,tf.float32),(tf.TensorShape([img_size,img_size]),tf.TensorShape([num_lmark,2])))
>     return dataset
> 
> return input_fn
> ```
> In dan_run_loop.py:
> 
> ```
> if flags.mode == tf.estimator.ModeKeys.PREDICT:
>     import cv2
>     predict_results = estimator.predict(input_function)
>     for x in predict_results:
>         landmark = x['s2_ret']
>         img = x['img']
>         img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
>         for lm in landmark:
>           cv2.circle(img, (lm[0], lm[1]), 1, (0,0,255), -1)
> 
>         # cv2.imshow('t',img)
>         # cv2.waitKey(30)
>         cv2.imwrite('data/image_predict.jpg', img)
>     return
> ```

do you know how to freezing this model to x.pb file?

**Comment by sljlp** [comment]
How fast does it work when changed for predicting one image?
I want to predict images with  only  some(about 30) cpus rather than any gpu.
Can the speed remain at most 1 sec  per image?

**Comment by dapipi0315** [comment]
> In DAN_V2.py:
> 
> ```
> def video_input_fn(data_dir,img_size,num_lmark):
> # video = cv2.VideoCapture(data_dir)
> 
> def _get_frame():
>     # while True:
>         # _,frame = video.read()
>         # if len(frame.shape) == 3:
>         #     frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
>     path = 'data/image.jpg'
>     img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
>     frame = cv2.resize(img,(img_size,img_size)).astype(np.float32)
>     yield (frame,np.zeros([num_lmark,2],np.float32))
> 
> def input_fn():
>     dataset = tf.data.Dataset.from_generator(_get_frame,(tf.float32,tf.float32),(tf.TensorShape([img_size,img_size]),tf.TensorShape([num_lmark,2])))
>     return dataset
> 
> return input_fn
> ```
> 
> In dan_run_loop.py:
> 
> ```
> if flags.mode == tf.estimator.ModeKeys.PREDICT:
>     import cv2
>     predict_results = estimator.predict(input_function)
>     for x in predict_results:
>         landmark = x['s2_ret']
>         img = x['img']
>         img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
>         for lm in landmark:
>           cv2.circle(img, (lm[0], lm[1]), 1, (0,0,255), -1)
> 
>         # cv2.imshow('t',img)
>         # cv2.waitKey(30)
>         cv2.imwrite('data/image_predict.jpg', img)
>     return
> ```

excuse me.Is the result of your training accurate? The landmarks are not in position.
