### ISSUE TITLE
Could you share your pre-trained models?

### ISSUE THREAD

**Issue by hangkaitan** [zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment#3]
Hi,
   Could you share your pre-trained models?

**Comment by zjjMaiMai** [comment]
https://pan.baidu.com/s/1o83h4H8
password : ttqp

**Comment by zhijun** [comment]
When trying to load this model, I got below
**`tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file model\Menpo68\checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`**

Code:
`saver = tf.train.import_meta_graph('model/Menpo68/TfModel.meta')`
My environment is Anaconda 3 with Python 3.6, Tensorflow-GPU 1.4.

**Comment by zjjMaiMai** [comment]
just use 
`Saver = tf.train.Saver()`

**Comment by hengshanji** [comment]
@zhijun  how do you restore the model ? I just change the DAN.py code:
Saver.restore(Sess,'./Model/Model')  to Saver.restore(Sess,'./Menpo68/TfModel') and it cannot work.

And where do you get the AllDataSet.npz ?   i just the meanshape.npy of Para.npz  instead.
