### ISSUE TITLE
What is the password for menpo trainset?

### ISSUE THREAD

**Issue by mariolew** [zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment#4]
I've downloaded the menpo trainset from ibug website, but the trainset.zip requires password to unzip, what is the password?

**Comment by MarekKowalski** [comment]
You need to get the password from the challenge organisers.

**Comment by ansj11** [comment]
do you have pre-trained model of TensorFlow, I want to test on TensorFlow

**Comment by hengshanji** [comment]
could you share the link of the mepo trainset and the pass word? @mariolew

**Comment by wujiexiaowugui** [comment]
Do you have the password to unzip the trainset? Can you share the password? Thank you so much! @mariolew
