### ISSUE TITLE
The Inference Speed

### ISSUE THREAD

**Issue by auroua** [zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment#6]
The paper says the inference speed of the model is  45 fps.
What about your model?
I found the pre-trained model is 279M which is very big.

**Comment by zjjMaiMai** [comment]
you can test it on your PC.
i use it on a real-time project , so I guess the speed [GTX 1080Ti] > 30 fps.

**Comment by auroua** [comment]
Thanks for your replay!
I will test it.

**Comment by auroua** [comment]
I have tested the inference time. The speed is 0.6655 seconds per-image, which is quite slow. How could you get real time? I am using titan xp.
