### ISSUE TITLE
transform function

### ISSUE THREAD

**Issue by wanglu0316** [zjjMaiMai/Deep-Alignment-Network-A-convolutional-neural-network-for-robust-face-alignment#8]
Hi, I cann't understand the transform function in DataSetPre.py
def transform(form,to):
    destMean = np.mean(to, axis=0)
    srcMean = np.mean(form, axis=0)

    srcVec = (form - srcMean).flatten()
    destVec = (to - destMean).flatten()
    a = np.dot(srcVec, destVec) / np.linalg.norm(srcVec) ** 2
    b = 0
    for i in range(form.shape[0]):
        b += srcVec[2 * i] * destVec[2 * i + 1] - srcVec[2 * i + 1] * destVec[2 * i] 
    b = b / np.linalg.norm(srcVec) ** 2

    T = np.array([[a, b], [-b, a]])
    srcMean = np.dot(srcMean, T)

    return T, destMean - srcMean

which algorithm have you used to transform the original landmark to the meanshape,what's the meaning of a, b and T?

**Comment by MarekKowalski** [comment]
Hi,

Please take a look at this answer to a previous question in the other Deep Alignment Network repo:
https://github.com/MarekKowalski/DeepAlignmentNetwork/issues/14

Best regards,

Marek
